import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

export default function Home({data}) {
  console.log(data.projects)
  const projects = data.projects.map((project, idx)=>{
    return(
      <div className="projectDiv" key={`project-${idx}`}>
        <h3>project title: {project.name}</h3>
        <p>{project.description}</p>
        {/* need to add images w/links for github and deployment */}
        <Link href={`${project.links.repo}`}>
        <Image 
                src="/GitHub-Mark-64px.png"
                alt='the vercel logo for demo purposes'
                width={50}
                height={50}
            />
          </Link>
        <p>tech used: {project.tech}</p>
      </div>
    )
  })
  return (
    <div>
      <Head>
        <title>andy olsen codes</title>
        <meta name="description" content="generated by me cause i'm sick" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="main-info">
          <h1>Hi - I'm Andy</h1>
          <h2>{"{"}full stack dev{"}"}</h2>
          {projects}
        </div>
      </main>
    </div>
  )
}

export async function getStaticProps(){
  // we can do all of our ajax/axios/fetch here
  // we can call external API's, express backend, next backend
  const res = await fetch(`${process.env.SERVER_URL}/api/projects`)
  const data = await res.json()
  return {
    props: { data }
  }
} 
