import Head from 'next/head'
import Navbar from '../components/navbar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>my sick portfolio</title>
        <meta name="description" content="generated by me cause i'm sick" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>My Portfolio</h1>
      </main>
    </div>
  )
}
